from enum import StrEnum

class FrameAttribute(StrEnum):
    """
    Enumeration of the different attributes of an ImageFrame object.
    """
    
    ACQ_ATTRIBUTES_TRANSFORMED = "Acq.AttributesTransformed"
    ACQ_CAMERA_ID = "Acq.Camera.ID"
    """The ID of the camera used for the acquisition."""
    ACQ_CAMERA_INDEX = "Acq.Camera.Index"
    """Index of the camera used for the acquisition. This is an array."""
    ACQ_CAMERA_LABEL = "Acq.Camera.Label"
    """Label of the camera (i.e. Camera 1, Camera 2)."""
    ACQ_TIME = "Acq.Time"
    """Time of the acquisition of this frame. This is an array."""
    ACQ_TIME_TO_TRIGGER = "Acq.TimeToTrigger"
    """Time to trigger of the acquisition of this frame. This is an array."""
    ACQ_TIME_SERIES = "AcqTimeSeries"
    CCD_EXPOSURE_TIME = "CCDExposureTime"
    """Exposure time of the camera. This is a string value with the unit."""
    CAM_PIXEL_SIZE = "CamPixelSize"
    """Pixel size of the camera. This is a string value with the unit."""
    CAMERA_MAX_INTENSITY = "CameraMaxIntensity"
    """Maximum intensity of the pixel values. This is a string value."""
    CAMERA_MAX_NX = "CameraMaxNx"
    """Maximum number of pixels in the x-direction. This is a string value."""
    CAMERA_MAX_NY = "CameraMaxNy"
    """Maximum number of pixels in the y-direction. This is a string value."""
    CAMERA_NAME = "CameraName"
    """Name of the camera."""
    FRAME_PROCESSING = "FrameProcessing"
    RGB_FRAME = "RGBFrame"
    """Whenever this is a RGB frame or not. This is a string value of 0 or 1."""

class BufferAttribute(StrEnum):
    """
    Enumeration of the different attributes of a Buffer object.
    """
    ACQ_INPUT_SPEED_SELECT = "Acq.Input.SpeedSelect"
    ACQ_INPUT_START_TRIGGER = "Acq.Input.StartTrigger"
    ACQ_STATUS_RECORD_POST = "Acq.Status.RecordPost"
    ACQ_TIME_SERIES = "AcqTimeSeries"
    CUSTOM_IMAGE_TAG_COUNT = "CustomImageTag_Count"
    DEV_DATA_ALIAS0 = "DevDataAlias0"
    DEV_DATA_ALIAS1 = "DevDataAlias1"
    DEV_DATA_ALIAS2 = "DevDataAlias2"
    DEV_DATA_ALIAS3 = "DevDataAlias3"
    DEV_DATA_ALIAS4 = "DevDataAlias4"
    DEV_DATA_CHANNEL0 = "DevDataChannel0"
    DEV_DATA_CHANNEL1 = "DevDataChannel1"
    DEV_DATA_CHANNEL2 = "DevDataChannel2"
    DEV_DATA_CHANNEL3 = "DevDataChannel3"
    DEV_DATA_CHANNEL4 = "DevDataChannel4"
    DEV_DATA_CLASS0 = "DevDataClass0"
    DEV_DATA_CLASS1 = "DevDataClass1"
    DEV_DATA_CLASS2 = "DevDataClass2"
    DEV_DATA_CLASS3 = "DevDataClass3"
    DEV_DATA_CLASS4 = "DevDataClass4"
    DEV_DATA_NAME0 = "DevDataName0"
    DEV_DATA_NAME1 = "DevDataName1"
    DEV_DATA_NAME2 = "DevDataName2"
    DEV_DATA_NAME3 = "DevDataName3"
    DEV_DATA_NAME4 = "DevDataName4"
    DEV_DATA_SCALE0 = "DevDataScale0"
    DEV_DATA_SCALE1 = "DevDataScale1"
    DEV_DATA_SCALE2 = "DevDataScale2"
    DEV_DATA_SCALE3 = "DevDataScale3"
    DEV_DATA_SCALE4 = "DevDataScale4"
    DEV_DATA_SCALE_I0 = "DevDataScaleI0"
    DEV_DATA_SCALE_I1 = "DevDataScaleI1"
    DEV_DATA_SCALE_I2 = "DevDataScaleI2"
    DEV_DATA_SCALE_I3 = "DevDataScaleI3"
    DEV_DATA_SCALE_I4 = "DevDataScaleI4"
    DEV_DATA_X0 = "DevDataX0"
    DEV_DATA_X1 = "DevDataX1"
    DEV_DATA_X2 = "DevDataX2"
    DEV_DATA_X3 = "DevDataX3"
    DEV_DATA_X4 = "DevDataX4"
    DEV_DATA_SOURCES = "DevDataSources"
    DEV_DATA_TRACE0 = "DevDataTrace0"
    DEV_DATA_TRACE1 = "DevDataTrace1"
    DEV_DATA_TRACE2 = "DevDataTrace2"
    DEV_DATA_TRACE3 = "DevDataTrace3"
    DEV_DATA_TRACE4 = "DevDataTrace4"
    EX_PATH_VALUE_F = "ExPathValue_f"
    LOAD_FILE = "LoadFile"
    """Source file of the buffer attributes and data. For `.im7` files this is the original `.im7` file for example."""
    LOAD_SET = "LoadSet"
    """Original set file from which this buffer was loaded. The extension (.set) is omitted."""
    LOAD_SET_INDEX = "LoadSetIndex"
    LOAD_SET_TYPE = "LoadSetType"
    TIMESTAMP = "Timestamp"
    """Timestamp in ISO format.
    
    See: https://en.wikipedia.org/wiki/ISO_8601
    """
    DAVIS_VERSION = "_DaVisVersion"
    """DaVis version used to create the buffer."""
    DATE = "_Date"
    """Can be empty."""
    HEADER_PACK_TYPE = "_Header_PackType"
    TIME = "_Time"
    """Can be empty. See Timestamp instead."""

