[project]
name = "lvpyioTools"
description = "A set of tools to handle LabView files and data via the lvpyio library."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12.3"
version = "2.4.4"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Simon Cadet", email = "simon.cadet@univ-poitiers.fr" },
]
dependencies = [
    "numpy",
    "matplotlib",
    "Pillow",
    "lvpyio>=1.4.0",
]
classifiers = [
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/SimKDT/lvpyio-tools"
Issues = "https://github.com/SimKDT/lvpyio-tools/issues"

[project.scripts]
lvpyioShow = "lvpyioTools.viewer:main"
